# Generated by Django 5.0 on 2024-10-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=50)),
                ('AdminEmail', models.EmailField(max_length=50, unique=True)),
                ('AdminPass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commuter',
            fields=[
                ('CommID', models.AutoField(primary_key=True, serialize=False)),
                ('CommName', models.CharField(max_length=50)),
                ('CommEmail', models.EmailField(max_length=50, unique=True)),
                ('CommPass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('ParkID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Station', models.CharField(choices=[('Sungai Buloh', 'Sungai Buloh'), ('Kampung Selamat', 'Kampung Selamat'), ('Kwasa Damansara', 'Kwasa Damansara'), ('Kwasa Sentral', 'Kwasa Sentral'), ('Kota Damansara', 'Kota Damansara'), ('Surian', 'Surian'), ('Mutiara Damansara', 'Mutiara Damansara'), ('Bandar Utama', 'Bandar Utama'), ('TTDI', 'TTDI'), ('Phileo Damansara', 'Phileo Damansara'), ('Pusat Bandar Damansara', 'Pusat Bandar Damansara'), ('Semantan', 'Semantan'), ('Muzium Negara', 'Muzium Negara'), ('Pasar Seni', 'Pasar Seni'), ('Merdeka', 'Merdeka'), ('Bukit Bintang', 'Bukit Bintang'), ('Tun Razak Exchange', 'Tun Razak Exchange'), ('Cochrane', 'Cochrane'), ('Maluri', 'Maluri'), ('Taman Pertama', 'Taman Pertama'), ('Taman Midah', 'Taman Midah'), ('Taman Mutiara', 'Taman Mutiara'), ('Taman Connaught', 'Taman Connaught'), ('Taman Suntex', 'Taman Suntex'), ('Sri Raya', 'Sri Raya'), ('Bandar Tun Hussein Onn', 'Bandar Tun Hussein Onn'), ('Batu 11 Cheras', 'Batu 11 Cheras'), ('Bukit Dukung', 'Bukit Dukung'), ('Sungai Jernih', 'Sungai Jernih'), ('Stadium Kajang', 'Stadium Kajang'), ('Kajang', 'Kajang'), ('Damansara Damai', 'Damansara Damai'), ('Sri Damansara Barat', 'Sri Damansara Barat'), ('Sri Damansara Sentral', 'Sri Damansara Sentral'), ('Sri Damansara Timur', 'Sri Damansara Timur'), ('Metro Prima', 'Metro Prima'), ('Kepong Baru', 'Kepong Baru'), ('Jinjang', 'Jinjang'), ('Sri Delima', 'Sri Delima'), ('Kentonmen', 'Kentonmen'), ('Jalan Ipoh', 'Jalan Ipoh'), ('Sentul Barat', 'Sentul Barat'), ('Titiwangsa', 'Titiwangsa'), ('Hospital Kuala Lumpur', 'Hospital Kuala Lumpur'), ('Raja Uda', 'Raja Uda'), ('Ampang Park', 'Ampang Park'), ('Persiaran KLCC', 'Persiaran KLCC'), ('Conlay', 'Conlay'), ('Chan Sow Lin', 'Chan Sow Lin'), ('Kuchai', 'Kuchai'), ('Taman Naga Emas', 'Taman Naga Emas'), ('Sungai Besi', 'Sungai Besi'), ('Serdang Raya Utara', 'Serdang Raya Utara'), ('Serdang Raya Selatan', 'Serdang Raya Selatan'), ('Serdang Jaya', 'Serdang Jaya'), ('UPM', 'UPM'), ('Taman Equine', 'Taman Equine'), ('Putra Permai', 'Putra Permai'), ('16 Sierra', '16 Sierra'), ('Cyberjaya Utara', 'Cyberjaya Utara'), ('Cyberjaya City Centre', 'Cyberjaya City Centre'), ('Putrajaya Sentral', 'Putrajaya Sentral')], max_length=50)),
                ('Level', models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], max_length=50)),
                ('BoxNo', models.CharField(choices=[(1, 'Box 1'), (2, 'Box 2'), (3, 'Box 3'), (4, 'Box 4'), (5, 'Box 5'), (6, 'Box 6'), (7, 'Box 7'), (8, 'Box 8'), (9, 'Box 9'), (10, 'Box 10'), (11, 'Box 11'), (12, 'Box 12'), (13, 'Box 13'), (14, 'Box 14'), (15, 'Box 15'), (16, 'Box 16'), (17, 'Box 17'), (18, 'Box 18'), (19, 'Box 19'), (20, 'Box 20'), (21, 'Box 21'), (22, 'Box 22'), (23, 'Box 23'), (24, 'Box 24'), (25, 'Box 25'), (26, 'Box 26'), (27, 'Box 27'), (28, 'Box 28'), (29, 'Box 29'), (30, 'Box 30')], max_length=50)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Commuter', 'Commuter')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PayID', models.AutoField(primary_key=True, serialize=False)),
                ('Method', models.CharField(choices=[('QR Code', 'QR Code'), ('Account Transfer', 'Account Transfer')], max_length=50)),
                ('Amount', models.IntegerField()),
                ('CommID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRT_Webapp.commuter')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ReserveID', models.AutoField(primary_key=True, serialize=False)),
                ('PlateNo', models.CharField(max_length=50)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('CommID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRT_Webapp.commuter')),
                ('ParkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRT_Webapp.parking')),
                ('PayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRT_Webapp.payment')),
            ],
        ),
    ]
