# Generated by Django 5.0 on 2024-10-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRT_Webapp', '0002_remove_reservation_date_remove_reservation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='PayID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MRT_Webapp.payment'),
        ),
    ]
